version: "3.11"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: black411_app
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    command: python src/app.py
    ports: -"5000:5000"
